[package]
name = "csv-rs"
version = "0.1.0"
authors = ["fangbaoshun <fangbaoshun@hygon.cn>"]
edition = "2021"
description = "Library for HYGON CSV"
readme = "README.md"
keywords = ["hygon", "csv"]

[features]
hw_tests = []

[dependencies]
openssl = "0.10.55"
openssl-sys = "0.9.90"
iocuddle = "0.1.1"
static_assertions = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.1"
codicon = "3.0"
rand = "0.8"
